baseURL = "https://monstershow.co/"
languageCode = "es-es"
title = "Monster Show"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Monster Show"
    copyright  = "&copy; Monster Show. Todos los derechos reservados"
    favicon = "static/images/favicon.png"
    description = "Monster Show"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    css = ["css/custom.css"]
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "javascript"]

[[menu.main]]
    url = "/monstershow"
    name = "Home"
    weight = 1
